# Generated by Django 3.2 on 2022-03-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_course_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='title',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.TextField(max_length=300),
        ),
    ]
